### ISSUE TITLE
Baked books: Chapter 38.4 Figure Aligment-Content in AP Bio

### ISSUE THREAD

**Issue by AliciaZong** [openstax/tutor-js#2530]
**SCENARIO** _Briefly describe the issue._
As attached the screenshot:
![38.4.jpeg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/82617607-c4be-43b0-96c7-9bdf4c12884c)
----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **Product:**
- [ ] Accounts 
- [ ] BigLearn
- [ ] Exercises 
- [ ] CNX
- [v] Tutor
- [ ] Payments
- [ ] Highlight 
- [v] Web

- **User Type:**
- [ ] Admin  
- [v] Content/QA
- [v] Student  
- [ ] Teacher
- [ ] N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  AP Bio

- **Steps**

----------------
**Environment:**

- **Instance:**
- [ ] production 
- [ ] qa 
- [ ] staging
- [ ] dev 
- [v] content 
- [ ] demo
- **OS:**
- [v] Mac OSX 
- [ ] Windows
- [ ] Android 
- [ ] iOS
- **Browser:**
- [v] Chrome 
- [ ] Firefox 
- [ ] Safari
- [ ] Opera 
- [ ] IE 
- [ ] Edge
- **Browser Version:**  
 72.0.3626.119
----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by carlycurran** [comment]
I think this duplicates a figure alignment card for AP Physics -- looks like same issue

**Comment by nathanstitt** [comment]
yep, close to the same cause as outlined in https://github.com/openstax/tutor-js/issues/2512 and was fixed in https://github.com/openstax/tutor-js/pull/2597

This is slightly different as that content markup doesn't make much sense.  it's an `os-figure` followed by an problem, but the problem has the exact same image, so it looks crazy.

It now looks like with the image fixes:

![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/42db2991-9c9e-455b-86f5-752fb9374b78)

**Comment by nathanstitt** [comment]
We discussed the double images in https://openstax.slack.com/archives/C1GEF8S0N/p1557333754050800

The second is because that's pulled in from exercises which also has the same image. It's unclear at this time how to fix that

**Comment by CaptainXep** [comment]
Verified in QA

**Comment by CaptainXep** [comment]
Verified in Staging. Misalignment will be fixed in production

**Comment by Brooke-Fail** [comment]
After more investigation, this is still occuring on Production with the most recent AP Bio version of 17.7. 
user: teacher01
Course Id: 5332

Screenshot:
https://drive.google.com/open?id=1E5NF1BZSK_PHUGv6dPoA1szSdRFi976J

Removing 5/22 milestone and moving card back to Ready to Code.

**Comment by carlycurran** [comment]
@openstaxalina we have discovered that -- in this case -- there is an image in the content, but that image is also in Exercises (with a question) and getting pulled into the content. We don't see a simple way to deal with this (that won't change if the content changes). Do you know why we have this situation happening -- it seems pretty rare?

**Comment by openstaxalina** [comment]
Noting here: this is assessment ID 10830.

@carlycurran I believe this is happening because the student **must**  be able to look at the graph to answer the question.  However, when we created AP Bio, we thought that students would have the Visual Connection feature as one step, then on the _next_ step they would see the question.  So we thought that we needed to have the graph in both places.  

I noticed that we're also seeing the duplication in the PDF and web formats, so thank you for helping us catch that.  

I would recommend that we (content team) remove the figure from the assessment.  The only place it would appear is in the Visual Connection feature. 

Do you have any concerns?  We could try my proposal and then reimport to confirm this resolves the issues.

**Comment by carlycurran** [comment]
@openstaxalina would that assessment show up in the Question Library without a figure, in that case?

**Comment by openstaxalina** [comment]
@carlycurran yes, it would

**Comment by openstaxalina** [comment]
@carlycurran there may be one other thing we can do - we can specify that the assessment "requires context" and _then_ I believe it would show up in the QL _with_ the figure.  Do you want me to make the change and reimport?

**Comment by carlycurran** [comment]
So, if we say that the question requires context, do you know if a teacher decides to assign it as a HW question -- does it bring in a figure? I'm not sure how _requires context_ works.

**Comment by carlycurran** [comment]
And yes, we can try to reimport!

**Comment by openstaxalina** [comment]
@carlycurran I believe that the context (in this case, figure) will be pulled in regardless of whether the question is reading or homework.  

I've added "requires-context" to assessment 10830 and this is ready for reimport.

**Comment by carlycurran** [comment]
@openstaxalina looks like that didn't work 😢

**Comment by carlycurran** [comment]
@openstaxalina, do you have to delete the figure from exercises?

**Comment by openstaxalina** [comment]
@carlycurran good point - just deleted the figure.  🤞 the issue is resolved this time...

**Comment by carlycurran** [comment]
darn. didn't work either 😫

**Comment by openstaxalina** [comment]
@carlycurran that's really strange.  are you sure that when you are importing, you are getting all new versions of the exercises?

**Comment by carlycurran** [comment]
@openstaxalina yes, I'm checking that box that discards old and gets new versions

**Comment by openstaxalina** [comment]
I'm not sure what's going on then.  I've completely removed the figure from the Exercise:
<img width="1436" alt="Screen Shot 2019-06-26 at 3 35 32 PM" src="https://user-images.githubusercontent.com/7863733/60212984-277b0c00-9828-11e9-93c5-af4bed756d97.png">


Is there any possibility of caching?

**Comment by carlycurran** [comment]
I don't think it's caching because I tried it on Tutor-demo, too.

**Comment by openstaxalina** [comment]
@carlycurran would you be able to link me to what you are looking at?

**Comment by carlycurran** [comment]
sure - log in to Teacher01 on tutor-demo and this is the page: https://tutor-demo.openstax.org/book/314/page/15128

**Comment by openstaxalina** [comment]
Carly and I discussed - for some reason, the assessment version isn't updated in the book/course.  The assessment is at version 8.  However, it should be at version 10 (screenshot above).  

Next steps: Carly to discuss with Nathan.

**Comment by carlycurran** [comment]
@openstaxalina re-baked and Carly re-imported. Extra figure was removed!!!! 

Closing this card
